---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rlwrgzez/conectica-live/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/rsync -a --exclude='.env' --exclude='storage/app/public' --exclude='public/storage' --exclude='node_modules' --exclude='vendor' ./ $DEPLOYPATH
